// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://sqqosreoovokcswpyjqj.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxcW9zcmVvb3Zva2Nzd3B5anFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE1NTM4NjQsImV4cCI6MjA0NzEyOTg2NH0.VBqLeaMckP9z-OnHb4ikOxU1HXxXymIk4ojzYE3OGxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);